FROM python:3.12-slim
WORKDIR /app
RUN apt-get update && \
    apt-get upgrade -y && \
    apt-get install -y git
COPY pyproject.toml uv.lock .
RUN pip install --no-cache-dir uv && \
    uv sync
COPY . .
EXPOSE 8000
CMD ["uv", "run", "fastapi", "run", "main.py"]