FROM python:3.12-slim
RUN apt-get update && \
    apt-get upgrade -y && \
    apt-get install -y git
RUN pip install --no-cache-dir uv && \
    uv sync
EXPOSE 8000
CMD ["uv", "run", "fastapi", "run", "main.py"]